name: itsindire
description: App y'amategeko y'umuhanga

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter_svg: any
  flutter:
    sdk: flutter

  provider: ^6.1.2
  percent_indicator: ^4.2.3
  flutter_spinkit: ^5.2.1
  url_launcher: ^6.2.6
  mailer: ^6.1.0
  connectivity_plus: ^6.0.3
  loading_animation_widget: ^1.2.1
  flutter_dotenv: ^5.1.0
  transparent_image: ^2.0.1
  flutter_local_notifications: ^17.1.2
  advance_pdf_viewer2: ^2.0.5+1
  cloud_firestore: ^5.1.0
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_messaging: ^15.0.3
  google_fonts: ^6.2.1
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/images/ic_launcher.png"
  android: true

  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # ASSETS OF THE APPLICATION
  assets:
    - assets/images/
    - .env
